### ISSUE TITLE
Player 1 movement

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#1]
Start with a box (or whatever) for a sprite

Simply to get a player one that can move around on the screen.

Elements:
Player script
Project settings for keyboard controls (consider looking into how these might be changed as a setting or option, we can add that as a feature later though)
some square sprite or something

**Comment by ghost** [comment]
Sent a PR. Have not looked into changing key settings as an option yet

**Comment by stannardtyler** [comment]
If doing any hit detection for the simple Sprite of the player or enemies, may I suggest using a triangle as it has the best shape for a ship like look.
