### ISSUE TITLE
player prefab speed is 0

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#118]
Set speed > 0. Say 100? seemed fine with my tests, feel free to experiment though.

**Comment by ghost** [comment]
Set default speed for the player prefab to be 100
#124

**Comment by ghost** [comment]
Reopening this, experiment with different player movement speeds

**Comment by flip40** [comment]
In that case removing bug tag.

**Comment by flip40** [comment]
Closing, current speed is 300. Should rename / create a new issue for determining player or other object move speeds in terms of game feel. At the moment, this is no longer a bug (not 0) nor is it high priority (300 is a working value, we can adjust it later as needed).
