### ISSUE TITLE
tracking ai broken?

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#120]
It appears that tracking ai is not working properly. Needs to be looked at.

**Comment by ghost** [comment]
In the past I think we were both testing bullets with our own playerBullets and enemyBullets, each with their Team component set to certain values. Enemies also had a Flag component which set them as 'trackable'

Can either create new player bullet prefabs and enemy bullet prefabs with Teams set accordingly, or can set values depending on the Team values in the root player or enemy gameobject. Will also need to add Flag components to the prefabs

For the first playable level, all enemies and players will have the trackable flag set to true?

**Comment by flip40** [comment]
Ah right, because previously (until recent changes we made) the bullets didn't have a Team, and now they use that to determine who to target (in part) right? And yes, in general all enemies and players should be trackable. Bullets should not be trackable... depending on implementation (we can mess around with it) we might make some missiles be able to track each other.

Do we not set the bullet / missile teams already by their parent? I think that is the best solution. Unique prefabs for which team each bullet belongs too could eventually effectively double our bullet count, just for the team setting...

**Comment by ghost** [comment]
Projectiles are not already setting their teams. Yeah that definitely sounds like a better solution than having unique prefabs
