### ISSUE TITLE
Scroll and RendererExtension for parallax scrolling

### ISSUE THREAD

**Issue by ghost** [DemoProductions/shmup#133]
They're currently a direct copy and paste from a PixelNest tutorial (something that I did to see how parallax scrolling can work a few months back). Develop scripts to fit the way we want parallax scrolling to work.

Discuss details of how we want parallax scrolling to work (I'll need to revisit old issues)

**Comment by flip40** [comment]
Parallax scrolling uses their scripts with different speeds for each layer. I think scrolling is fine with their script for now, feel free to reopen if you disagree.
