### ISSUE TITLE
Remove bullets after leaving screen

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#14]
Pretty self explanatory, bullets should be removed when they exit the screen somehow.

Not sure if using triggers would be the best way, perhaps just having them delete themselves after having traveled a certain distance from the player? Just looking to avoid having bullets unintentionally disappear while still on the screen (assuming we want them to go across the entire screen, anyways).

**Comment by ghost** [comment]
May depend on the kind of game we have. Will the player be limited to just the screen or will the player be able to move the camera around

**Comment by flip40** [comment]
Forget where it was but we have discuss the screen moving somewhere... can't remember where, guess we can restart it here though. Personally I think we should not have a moving screen, as by doing so we make everything visible. You won't miss a pickup because you didn't see it off screen, or have enemies shooting at you when you can't even see them. That is just my opinion though.

Regardless of our decision there, we need some form of off screen bullet removal. As these games are scrollers, even if we allow the player to move the screen around, it is still going to be limited movement with a boundary, and we should remove bullets that go out of this boundary as they will not be coming back (unless we have some curvy homing rockets or some such shenanigans, so we should make sure there is enough room for them to really be gone).

Unless we want the player to have full movement control, but I think that doesn't fit the nature of these games, and removes time or pressure to keep going.

**Comment by flip40** [comment]
I mean heck, we are still early enough where we could change a bit and go for some sort of "Descent" style game, randomly generate levels but make it more of a 1 life exploration rogue-like game. Not sure that kind of game would run well with multiple players, but maybe we could make it work (or just not have multiple players in that case).

Not to throw our game plan out the window or anything, just throwing out an idea that occurred to me with what kind of game we could shoot for if we allowed full player control instead of scrolling.

This is a similar idea to what I described here, although unlike the 2d version we would end up with, this is truly a 3d and 6 degrees of freedom in the style of Descent: http://store.steampowered.com/app/327880/

**Comment by ghost** [comment]
Ah I agree with you. Having the player control their own movements and the camera would add a lot of complexity and it wouldn't really be a shmup. 

How do you think we will implement enemies? I saw a tutorial in the past where the enemies are already laid out on the map, but activate once they are within the boundaries of the camera (the camera and player would move together). Enemies were also invincible when they were not yet activated or live. And bullets were destroyed after a certain time interval. It might be easier and also less laggy to just destroy the bullets once it leaves the camera boundaries.

**Comment by flip40** [comment]
I agree with the camera boundaries, though still noting the caveat that depending on some possible bullet styles we might want the out of bounds to be a bit farther than the edge of the screen, but more or less the same idea.

Not sure on enemies, though that sounds like a good idea, as we can see a mapping of sorts as to the enemy order and adjust their arrival times and such easily (at least, it sounds like it would be nice for design adjustments).

**Comment by ghost** [comment]
I'm thinking of doing this by having colliders that surround the camera, a bit farther a way from the camera though so we avoid bullets disappearing on screen. When the bullets hit the colliders they disappear. So this would be similar to how I kept the player on screen
