### ISSUE TITLE
Keep player on screen

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#15]
Might just be able to use this: http://answers.unity3d.com/questions/174958/keeping-the-player-inside-the-screen.html

**Comment by ghost** [comment]
A less programmatic way would be to surround the main camera with colliders. Will look more into the referenced link later tonight.

**Comment by flip40** [comment]
Hm, might work. The problem I wanted to avoid is the potential different camera sizes based on screen dimensions or resolution and such... if the colliders are children to the camera it might work.
