### ISSUE TITLE
Parallax scrolling

### ISSUE THREAD

**Issue by ghost** [DemoProductions/shmup#19]

**Comment by flip40** [comment]
Description? Just not sure if this is to make the background appear to be scrolling in parallax or if it is actual movement. Was going to set some issues for adding the line of enemies as well as screen scrolling, but we might need to figure out how exactly that will work. I assume we want to actually move the screen (as opposed to having it appear to be moving, when it really isn't), but I don't know how exactly the enemy implementation works.

I think you mentioned you had found a guide at some point for placing enemies that would then activate when they entered the screen? Would you be able to post a link to that?

**Comment by ghost** [comment]
Enemies that activate when they enter the screen in this link. Camera is actually moving and the background repeats: http://pixelnest.io/tutorials/2d-game-unity/parallax-scrolling/

**Comment by flip40** [comment]
great link, seems like a very useful resource for getting the parallax and enemy "spawning" working properly.

**Comment by ghost** [comment]
next addition is enemy 'activation' when the camera reaches them

**Comment by ghost** [comment]
When playing on a maximized window, can see the right part of the screen turn blue at times (the background color for the main camera).
