### ISSUE TITLE
Camera player walls are visible on widescreen (16:9, 16:10)

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#24]
![screen shot 2016-02-25 at 8 22 35 am](https://cloud.githubusercontent.com/assets/10754057/13326011/15e2e4a8-db99-11e5-810e-47d234d54bb8.png)

**Comment by ghost** [comment]
Have to go with the harder approach then -_-

And probably do something similar for the bulletWalls

**Comment by flip40** [comment]
Yeah, unfortunately.

Here's a copy of that link again from the last issue: http://answers.unity3d.com/questions/174958/keeping-the-player-inside-the-screen.html

We could probably adjust this for the bullet wall too, but perhaps use a similar component to see if the bullet has been off the screen for too long (a few seconds, perhaps), then just destroy it.
