### ISSUE TITLE
Abstract enemy class (AI)

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#52]
This mostly for AI reasons. Much of the start() or other pieces might not need to be copy-pasted repeatedly, but we need the update to do different things depending on how the AI should act.

We might also consider making component scripts that add to the enemy AI patterns. Take TrackingAI for example. If you put it on a non-moving object, you could effectively have a turret, despite the fact the script was initially created with missiles in mind. The idea is that you can take a GameObject (prefab) and create a unique AI simply by adding a unique set of AI scripts that could be adjusted, rather than having to create (or copy paste together) a unique piece of code to mix and match AI.

**Comment by flip40** [comment]
Going to work on this on the way home.

**Comment by ghost** [comment]
#60
