### ISSUE TITLE
Random wave spawner

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#69]
I'll flesh this out more later but what I thought up last night and at least want to get the basic idea written down...
- LevelController (probably a high level class that could server more functions than this too, but a necessary part). This class would handle what level we were on, and specify the waves that would be allowed to be spawned.
- WaveController (might bundle into LevelController...) would choose random Waves and spawn them at regular intervals (changeable by variable).
- Wave would be a class and gameobject (prefabs!) that would hold a list of Spawnables (defined as part of that script, only used there). It would trigger these Spawnables to spawn their gameobjects relative to themselves. OnInspecterGUI could be used to make this maneageable (show where they would be spawning on screen relative to the Wave object).
- Spawnable would be a class used by Wave that simply holds a gameobject and and x and y coordinate of where to spawn (relative to Wave object).

**Comment by ghost** [comment]
Initial Wave and Spawnable #70

**Comment by ghost** [comment]
A separate class for level generation if we are going to keep a static copy of the level graph?

**Comment by ghost** [comment]
Related: #71 WaveEditor snap functionality

**Comment by flip40** [comment]
Yeah, I think that makes sense. Not quite sure where to fit it off the top of my head, but LevelController will still need some other piece of code to handle telling it what level it is on. Since the Levels themselves are pieces of the map, the map code should also likely be used in part to say "this is the next level, start it up" to the LevelController when the game scene starts. (or in reverse, the LevelController needs to be able to ask a different source "what level are we on?")

**Comment by ghost** [comment]
With regards to the Random Wave Spawner (if I'm understanding this correctly), we wanted waves to generate on the fly (through position and time in the level parameters?) This is on hold for now right (until the playable first level)? In the playable first level, waves are placed manually on the scene and then individual enemies are activated upon entering the main camera

Or is the RandomWaveSpawner referring to the LevelController, WaveController, etc as a whole

**Comment by flip40** [comment]
"Random Wave Spawner" was perhaps bad phrasing for the title as it implies an object itself. This turned into LevelController and Wave classes (WaveController's description was done in LevelController).

This needs some work (I think I might have other issues that target adding proper randomization and such EDIT: #79), but it is good enough for now. At the moment it will spawn each wave in the list a certain distance apart (via variable in the editor, you can see the "Wave windows" when it is selected in the scene). As such, we can currently use this for the first level if we want.

**Comment by flip40** [comment]
Think we should close this? Looks to be a bit old at this point. There are a few other issues above this one that seem to take on the issues required to continue this, so I am not sure we still need this issue around.

#72 #79 #84 #91 #92

**Comment by ghost** [comment]
Yeah lets close this and continue discussion in the issues mentioned above
