### ISSUE TITLE
LevelController class

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#72]
Add a level controller class. Determines what waves can spawn in each level and defines other properties based on level (background prefab, middleground prefab, etc).

As a side note since mentioned here, we need background and middleground as prefabs and just stuff these in level folders inside a resource folder for loading. Will make life easy later for loading different levels in one scene... I'll make another issue discussing this further.

**Comment by ghost** [comment]
Just some ideas on background and middlegrounds we can have.

Background
- Star variations (maybe can have like 3 of these)
- Color variations 

Middleground
- Closer stars
- Planets/Faction planets
- Ships

**Comment by flip40** [comment]
I think we should have more than just "stars" in the background (in terms of star variation). We should include nebula or other interesting cosmic objects to take up much of the background (if just because stars alone are pretty empty).

Good ideas though.

**Comment by ghost** [comment]
#76

**Comment by stannardtyler** [comment]
I agree with the backdrop to have other object, jus always make sure to dim the background abit and highlight the sprites so no lose of sight for projectiles or enemy ships. Of course would be interesting to have stages where the background plays with visual elements!
