### ISSUE TITLE
Add Resource folder and subfolders

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#73]
To help with level to level changes without worrying too much about have a new scene for each level, I would propose we effectively "export" our scene setup into prefabs loadable by a LevelController. Levels should be stored in the Resource folder (see Resource.Load and Resource.LoadAll in unity api), and each level should have its own folder with their unique contents. For example, level1 and level2 should both have a foreground prefab, middleground prefab, and so on.

We can abstract this, though for simplicity and since we have a rather low number of levels I think it would be best to just define things in LevelController and have unique prefabs of objects in each level.

We could possibly also have a unique "waves" folder in each level to contain unique enemies for those levels...

We could also add a LevelController editor. It would handle easily managing saving configurable options for each level (for example, what waves can be spawned in each level).

**Comment by ghost** [comment]
Couple of possible gotchas that I remember struggling with regarding the Resources folder
- the resources folder has to be capitalized - "Resources"
- Issues with sub directories? Ex: Can get assets from Resources/test but not Resources/test/images

**Comment by ghost** [comment]
#76

**Comment by flip40** [comment]
hm, should this be closed? We might need to finalize movement of files into Resources though (I think currently I just cloned them into resources, leaving old copies in Assets...)

**Comment by flip40** [comment]
actually I'll leave this open and move all prefabs into Resources folders...

**Comment by flip40** [comment]
Should this be closed? Not sure there is anything to do here, we did move most everything in terms of prefabs (I think).

**Comment by flip40** [comment]
Oh, I should have refreshed my tab ^.^
