### ISSUE TITLE
Unity version

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#8]
Current Unity version seems to be 5.3.2, if possible we should all upgrade to this version to keep things uniform.

![screen shot 2016-02-14 at 5 05 47 pm](https://cloud.githubusercontent.com/assets/10754057/13037770/0f58fdf2-d33d-11e5-9dea-9f6b3b1b20a3.png)

**Comment by ghost** [comment]
5.3.2 sounds good

**Comment by flip40** [comment]
now using 5.3.5f1

**Comment by flip40** [comment]
I think we are on the same version at this point. If we ever want to consider changing to another version (or need to), then we can reopen this.

**Comment by flip40** [comment]
Due to getting a new laptop I was forced to also get a newer version of Unity. Hopefully as we are only passing code around this isn't a huge issue, but just in case I wanted to let you know that I am using Unity version 5.5.0f3.

**Comment by ghost** [comment]
Alright I'm using 5.5.0f3 now too

**Comment by flip40** [comment]
5.5.0f3 is the current version, added in repo as well (some file or other keeps track of this...)
