### ISSUE TITLE
LevelController does not initiate foreground

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#84]
LevelController needs to initiate a foreground object of some sort to place the players in. Foreground has the camera linked scrolling script. Anything that needs to follow the player (drones, other players, etc.) belong in the foreground. I think at some level the foreground must be dynamically populated (what player type to spawn, number of players, etc.), so we might need to either have LevelController handle this, or add an appropriate script to our Foreground element.

**Comment by ghost** [comment]
Maybe we can focus on just setting the player location based on the number of players for now. Players can spawn along some vertical line, or have designated regions for players 1-4 in a zigzag sort of shape. Not sure on how spawn based on player ship type or drones will go yet. What do you think about that? More cumbersome ships spawn a bit more to the left than lighter and faster ships?

**Comment by flip40** [comment]
Perhaps. I think at the very least we should spawn in ships along predefined points like you said.

Having cumbersome ships spawn a bit more to the left sounds like a good idea, however to not overcomplicate it we should probably still rely on set spawn locations (either by code or by gameobject... one of the projects last semester we used "powerup spawners" as a way to define these locations, this could perhaps be done here as well but for player spawn locations).
