### ISSUE TITLE
Add Boss to LevelController

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#91]
This is partially there, but I need to properly implement it in the editor...

**Comment by ghost** [comment]
Would be nice if we have some way to edit boss states and the amount states that a boss would have in the editor

**Comment by flip40** [comment]
I agree, though I think that would fall under control of the Boss itself, not LevelController. LevelController just lets us set the boss for the level.

Unless we want to be able to vary the stages a boss has based on the level? Not sure if this would be useful though.

**Comment by flip40** [comment]
By the way, define boss states. Do you mean this in terms of "stages" (as hp lowers, it starts to act differently) or just in terms of varying attack patterns that it might use?

**Comment by ghost** [comment]
States in terms of what the boss can do depending on certain parameters. The boss can start out with a certain list of attack patterns. These attack patterns can change based on the boss's health, the length of the boss fight, or something else. And this can be defined through the animator state machines (think you mentioned this in another post). So maybe all enemies could idle, move, basic attack, and all bosses could idle, move, basic attack, special attack 1, special attack 2, special attack 3, unique boss movement1, etc.

But yeah abstracting the creation of bosses sounds pretty difficult haha. Think you mentioned that in another thread too.

**Comment by flip40** [comment]
Yeah, lets worry about abstraction for later, so we can at least get a simple boss working then use that as a basis for figuring out how to abstract it further... The simple solution is just a small state machine that causes behavioral changes on timers, and randomly (or less than randomly, depending on design of the boss) selecting a weighted behavior.

**Comment by flip40** [comment]
#135 and #143
