### ISSUE TITLE
First playable level sprites

### ISSUE THREAD

**Issue by ghost** [DemoProductions/shmup#96]
Player ship 

Starter weapon (not sure what to name this; this will be attached to the player ship, possible on top of it)

Single bullets

Enemy 1 - Moves in sin/cos wave motion and exits through the top or bottom of the screen; shoots single bullets 

Enemy 2 - Moves linearly from right to left; shoots single bullets

Enemy 3 - Same as Enemy 1 but shoots single missiles (not necessarily the same sin/cos wave)

Enemy 4 - Same as Enemy 1 but shoots tracking missiles (not necessarily the same sin/cos wave)

Enemy weapon 1
Single bullets

Enemy weapon 2
Single missiles

Enemy weapon 3
Tracking single missiles

Boss 1 - Maybe make this two times the size of the player

Boss weapon
Double bullets?
Single missiles?
Double missiles?
Tracking missiles?

Healthbar - See #75. Healthbar will be a "number of hits" healthbar
Need to make decision on whether we want round styled health nodes or square styled ones.
Full health node
Empty health node

Asteroids - maybe about 3 variations

Background

Middleground
Planets

What do you think? All of the above subject to changes still. 64x64 as the base size of sprites? What other sprites do you think we will need for a first playable level?

**Comment by flip40** [comment]
A few notes here for good possible reference, but the general gist of this issue and discussion have since been solved.
>  Discussion of specifics should get their own issue when appropriate (i.e. issue for discussing enemy type designs, weapon designs, wave designs, etc).
