### ISSUE TITLE
First playable level prefabs

### ISSUE THREAD

**Issue by ghost** [DemoProductions/shmup#98]
Prefabs for:
- background
- middleground(s)
- foreground
- enemies
- waves
- healthbars
- weapons
- bullets
- boss

**Comment by flip40** [comment]
No description.. "Add prefabs for the first playable level" ?

**Comment by ghost** [comment]
Sorry about that, forgot to edit this. Will need to settle on prefabs for:
- background
- middleground(s)
- foreground
- enemies
- waves
- healthbars
- weapons
- bullets
- boss

And I should try to make issues smaller haha

**Comment by flip40** [comment]
Closing, we have prefabs for all of these. Discussion of specifics should get their own issue when appropriate (i.e. issue for discussing enemy type designs, weapon designs, wave designs, etc).
